language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - php: 5.5
      env:
        - EXCLUDE_AMQP_INTEROP=true
        - EXCLUDE_STOMP=true
  fast_finish: true


services:
  - mysql
  - postgresql
  - redis-server
  - rabbitmq
  - docker

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo beanstalkd -v
  - sudo service beanstalkd start
  - docker pull webcenter/activemq
  - docker run -d -p 61613:61613 webcenter/activemq
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then pecl install igbinary-2.0.8; else pecl install igbinary; fi

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - if [ "$EXCLUDE_AMQP_INTEROP" = true ]; then travis_retry composer remove "enqueue/amqp-lib" "enqueue/amqp-tools" --dev --no-interaction  --no-update; fi
  - if [ "$EXCLUDE_STOMP" = true ]; then travis_retry composer remove "enqueue/stomp" --dev --no-interaction  --no-update; fi
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE yii2_queue_test;'
  - php tests/yii mysql-migrate --interactive=0
  - php tests/yii sqlite-migrate --interactive=0
  - psql -c  'create database yii2_queue_test;' -U postgres
  - php tests/yii pgsql-migrate --interactive=0

script:
  - vendor/bin/phpunit
