name: ci

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

  schedule:
    # every day at 1:15 and 12:15 UTC
    - cron: '15 1,12 * * *'

env:
  COMPOSE_PROJECT_NAME: yii2-queue
  COMPOSE_FILE: tests/docker-compose.yml
  AWS_SQS_ENABLED: ""
  AWS_SQS_URL: ""
  AWS_KEY: ""
  AWS_SECRET: ""
  AWS_REGION: ""
  AWS_SQS_FIFO_ENABLED: ""
  AWS_SQS_FIFO_URL: ""
  AWS_SQS_FIFO_MESSAGE_GROUP_ID: ""

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ 80, 81, 82 ]
        # does not support php>=8.1 for now, see https://github.com/opis/closure/issues/128

    steps:
      - uses: actions/checkout@v3

      - name: Setup Permissions
        run: |
          chmod a+x tests/docker/php/entrypoint.sh
          chmod a+x tests/docker/wait-for-it.sh
          chmod a+x tests/docker/php/mysql-lock.php
          chmod a+x tests/yii

      - name: PHPUnit
        run: make test${{ matrix.php }}
