name: build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  COMPOSE_PROJECT_NAME: yii2-queue
  COMPOSE_FILE: tests/docker-compose.yml
  AWS_SQS_ENABLED: ""
  AWS_SQS_URL: ""
  AWS_KEY: ""
  AWS_SECRET: ""
  AWS_REGION: ""
  AWS_SQS_FIFO_ENABLED: ""
  AWS_SQS_FIFO_URL: ""
  AWS_SQS_FIFO_MESSAGE_GROUP_ID: ""
jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 73, 74 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHP Unit tests for PHP ${{ matrix.php }}
        run: make test${{ matrix.php }}
